[project]
name = "nlu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "rasa>=3.6.21",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
]
